export const cats = [
  {
    name: "Frank",
    avatar: "images/cat-brownEyes.jpg",
    age: 8,
    bio: "Hey beautiful",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Meg",
    avatar: "images/cat-butterfly.jpg",
    age: 2,
    bio: "Do you like nature?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Holly",
    avatar: "images/cat-glasses.jpg",
    age: 5,
    bio: " Cool cat",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Sage",
    avatar: "images/cat-greenEyes.jpg",
    age: 10,
    bio: "What?  Nooooo!",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Amber",
    avatar: "images/cat-kitten.jpg",
    age: 7,
    bio: "hissssssssssss",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Chris",
    avatar: "images/cat-lookUp.jpg",
    age: 40,
    bio: "Touch me",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
];
